name: SQL Validation

on:
  pull_request:

jobs:
  lint-sql:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install SQLFluff
        run: pip install sqlfluff

      - name: Run SQL Linter
        run: sqlfluff lint .
